/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sasi-kathimanda' at '4/9/16 5:44 PM' with Gradle 2.8
 *
 * @author sasi-kathimanda, @date 4/9/16 5:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
